/*	
*  Nama	        : M. Ikhsan Fadhilah - M. Zidan Yohanza - Rifqi Muhadzib Ahdan - M. Faris Ary Prasetyo
*  NPM		: 140810210003 - 140810210021 - 140810210029 - 140810190056
*  Kelas        : A
*  Tanggal	: 30 November 2022
*  Deskripsi	: Program management sistem biaya parkir menggunakan java swing (Waktu dengan system)
**/
package App;
import KendaraanPackage.*;
import StrukturData.*;
import WaktuPackage.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import java.time.LocalDateTime;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author asus
 */
public class SistemParkirWaktuSistem extends javax.swing.JFrame {
    private DaftarKendaraan listKend = new DaftarKendaraan(); 
    private int totalBiaya = 0, row = 0;
    

    /**
     * Creates new form SistemParkir
     */
    public SistemParkirWaktuSistem() {
        initComponents();
    }
    
    public void setList(DaftarKendaraan listKend) {
        this.listKend = listKend;
    } 
    
    public DaftarKendaraan getList() {
        return this.listKend;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jkButtonGroup = new javax.swing.ButtonGroup();
        kendaraanButtonGroup = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        platField = new javax.swing.JTextField();
        brandField = new javax.swing.JTextField();
        bpkbField = new javax.swing.JTextField();
        motorRadioButton = new javax.swing.JRadioButton();
        mobilRadioButton = new javax.swing.JRadioButton();
        trukRadioButton = new javax.swing.JRadioButton();
        stnkField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        namaField = new javax.swing.JTextField();
        simField = new javax.swing.JTextField();
        ktpField = new javax.swing.JTextField();
        umurField = new javax.swing.JTextField();
        pRadioButton = new javax.swing.JRadioButton();
        lRadioButton = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        makeButton = new javax.swing.JButton();
        ubahButton = new javax.swing.JButton();
        hapusButton = new javax.swing.JButton();
        simpanButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        batalButton = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        kendaraanTable = new javax.swing.JTable();
        jScrollBar1 = new javax.swing.JScrollBar();
        jLabel17 = new javax.swing.JLabel();
        totalBiayaLabel = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        insertLastButton = new javax.swing.JButton();
        insertFirstButton = new javax.swing.JButton();
        insertAfterButton = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        deleteLastButton = new javax.swing.JButton();
        deleteFirstButton = new javax.swing.JButton();
        deleteAfterButton = new javax.swing.JButton();
        deleteCariButton = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(0, 102, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Data Parkir Kendaraan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(347, 347, 347))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel2.setText("Jenis :");

        jLabel3.setText("Plat No :");

        jLabel4.setText("Brand :");

        jLabel5.setText("BPKB :");

        platField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                platFieldActionPerformed(evt);
            }
        });

        kendaraanButtonGroup.add(motorRadioButton);
        motorRadioButton.setText("Motor");

        kendaraanButtonGroup.add(mobilRadioButton);
        mobilRadioButton.setText("Mobil");

        kendaraanButtonGroup.add(trukRadioButton);
        trukRadioButton.setText("Truk");

        jLabel7.setText("STNK :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(motorRadioButton)
                        .addGap(42, 42, 42)
                        .addComponent(trukRadioButton))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mobilRadioButton)
                            .addComponent(platField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(brandField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(stnkField)
                    .addComponent(bpkbField, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(motorRadioButton)
                            .addComponent(trukRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mobilRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(platField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(bpkbField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(stnkField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brandField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18))
        );

        jLabel9.setText("Nama :");

        jLabel10.setText("SIM :");

        jLabel11.setText("KTP :");

        jLabel12.setText("Umur :");

        jLabel13.setText("JK :");

        jkButtonGroup.add(pRadioButton);
        pRadioButton.setText("P");

        jkButtonGroup.add(lRadioButton);
        lRadioButton.setText("L");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ktpField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(simField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(namaField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pRadioButton))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(umurField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel13)
                    .addComponent(namaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pRadioButton)
                    .addComponent(lRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(simField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(umurField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(ktpField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel14.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Input Person");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Input Kendaraan");

        makeButton.setText("Make New");
        makeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeButtonActionPerformed(evt);
            }
        });

        ubahButton.setText("Ubah");
        ubahButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahButtonActionPerformed(evt);
            }
        });

        hapusButton.setText("Hapus");
        hapusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusButtonActionPerformed(evt);
            }
        });

        simpanButton.setText("Simpan");
        simpanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanButtonActionPerformed(evt);
            }
        });

        exitButton.setBackground(new java.awt.Color(204, 0, 0));
        exitButton.setForeground(new java.awt.Color(255, 255, 255));
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        batalButton.setText("Batal");
        batalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(makeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(hapusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(simpanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(ubahButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(batalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(makeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hapusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(simpanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(batalButton)
                    .addComponent(exitButton)
                    .addComponent(ubahButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jLabel16.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Menu");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Data Parkir");

        kendaraanTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Plat", "Jenis", "Masuk", "Keluar", "Jam Durasi", "Biaya", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        kendaraanTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kendaraanTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(kendaraanTable);

        jLabel17.setText("Total Biaya : ");

        jLabel19.setBackground(new java.awt.Color(204, 0, 0));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 0, 0));
        jLabel19.setText("Double click for detail");

        jPanel6.setBackground(new java.awt.Color(0, 102, 51));

        insertLastButton.setText("Insert Last");
        insertLastButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertLastButtonActionPerformed(evt);
            }
        });

        insertFirstButton.setText("Insert First");
        insertFirstButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertFirstButtonActionPerformed(evt);
            }
        });

        insertAfterButton.setText("Insert After");
        insertAfterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertAfterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(insertAfterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(insertLastButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(insertFirstButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)))
                .addGap(30, 30, 30))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(insertFirstButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(insertLastButton)
                .addGap(18, 18, 18)
                .addComponent(insertAfterButton)
                .addGap(29, 29, 29))
        );

        jLabel20.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Insert");

        jPanel7.setBackground(new java.awt.Color(0, 102, 51));

        deleteLastButton.setText("Delete Last");
        deleteLastButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteLastButtonActionPerformed(evt);
            }
        });

        deleteFirstButton.setText("Delete First");
        deleteFirstButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteFirstButtonActionPerformed(evt);
            }
        });

        deleteAfterButton.setText("Delete After");
        deleteAfterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAfterButtonActionPerformed(evt);
            }
        });

        deleteCariButton.setText("Delete yg Dicari");
        deleteCariButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCariButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(deleteCariButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(deleteAfterButton, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                        .addComponent(deleteLastButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteFirstButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(27, 27, 27))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deleteFirstButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(deleteLastButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteAfterButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteCariButton)
                .addGap(17, 17, 17))
        );

        jLabel18.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Delete");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(totalBiayaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(16, 16, 16))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addGap(236, 236, 236)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(132, 132, 132)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(128, 128, 128))
                                .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(444, 444, 444)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel21)
                                .addComponent(jLabel19)
                                .addComponent(jLabel20))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(totalBiayaLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 3, Short.MAX_VALUE))
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    private Kendaraan createKend() {
        Kendaraan newKend = new Kendaraan();
        String jenis = "", jk = null;
        
        if(motorRadioButton.isSelected()){
            jenis = "Motor";
        } else if(mobilRadioButton.isSelected()){
            jenis = "Mobil";
        } else if(trukRadioButton.isSelected()){
            jenis = "Truk";
        }
        
        if(lRadioButton.isSelected()){
            jk = "L";
        } else if (pRadioButton.isSelected()){
            jk = "P";
        }
        try{
            // Proses input kendaraan
            LocalDateTime currTime = LocalDateTime.now();
            
            newKend = newKend.getClassKendaraan(jenis);
            newKend.setJenis(jenis);
            newKend.setPlatKend(platField.getText());
            newKend.setNamaBrand(brandField.getText());
            newKend.setBpkb(bpkbField.getText());
            newKend.setStnk(stnkField.getText());
            // Input waktu berdasarkan waktu local sekarang
            newKend.getDatang().setJam(currTime.getHour());
            newKend.getDatang().setMenit(currTime.getMinute());
            newKend.getDatang().setDetik(currTime.getSecond());
            newKend.getDatang().fixTime();

            // Proses input person
            newKend.getPersons().setNama(namaField.getText());
            newKend.getPersons().setSim(simField.getText());
            newKend.getPersons().setKtp(ktpField.getText());
            newKend.getPersons().setJk(jk);
            int umur = Integer.parseInt(umurField.getText());
            newKend.getPersons().setUmur(umur);
        } catch (Throwable t){
            JOptionPane.showMessageDialog(null, "Silakan input nilai numeric umur!");
            newKend = null;
        }
        
        
        return newKend;
    }
    
    private void clearKendaraan(){
        kendaraanButtonGroup.clearSelection();
        platField.setText("");
        brandField.setText("");
        bpkbField.setText("");
        stnkField.setText("");
    }
    
    private void clearPerson() {
        namaField.setText("");
        simField.setText("");
        ktpField.setText("");
        umurField.setText("");
        jkButtonGroup.clearSelection();
    }
    
    private void deleteLastButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteLastButtonActionPerformed
        int confirm = JOptionPane.showConfirmDialog(null, "Yakin dihapus?", "Hapus", 1);
        if(confirm == 0){
            DefaultTableModel dm = (DefaultTableModel)kendaraanTable.getModel();
            String[] dataKosong = {"", "", "", "", "", "", "", ""}; // Data counter
        
            listKend.deleteLast();
            dm.removeRow(this.row);
            dm.addRow(dataKosong); // Counter agar row tidak berkurang
            kendaraanTable.validate(); 
            setTable();
        }        
        
        ubahButton.setEnabled(true);
        hapusButton.setEnabled(true);
        makeButton.setEnabled(true);
        simpanButton.setEnabled(false); 
        batalButton.setEnabled(false);
        setDisabledKomponen();
    }//GEN-LAST:event_deleteLastButtonActionPerformed

    private void deleteAfterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAfterButtonActionPerformed
        try{    
            if(row != 0){
                int row = kendaraanTable.getSelectedRow();
                String platPatokan = kendaraanTable.getValueAt(row, 1).toString();
                listKend.deleteAfter(listKend.linearSearch(platPatokan)); 
                
                DefaultTableModel dm = (DefaultTableModel)kendaraanTable.getModel();
                String[] dataKosong = {"", "", "", "", "", "", "", ""}; // Data counter

                int confirm = JOptionPane.showConfirmDialog(null, "Yakin hapus?", "Hapus", 1);
                if(confirm == 0){
                    setTable();
                    dm.removeRow(row);
                    dm.addRow(dataKosong); // Counter agar row tidak berkurang
                    kendaraanTable.validate(); 
                    setTable();
                    
                    ubahButton.setEnabled(true);
                    hapusButton.setEnabled(true);
                    makeButton.setEnabled(true);
                    simpanButton.setEnabled(false); 
                    batalButton.setEnabled(false);
                }
            }  
        } catch (Throwable e){
            JOptionPane.showMessageDialog(null, "Pilih row sebagai patokan");
        }
    }//GEN-LAST:event_deleteAfterButtonActionPerformed

    private boolean inputIsEmpty(){
        return(!(motorRadioButton.isSelected() || mobilRadioButton.isSelected() || trukRadioButton.isSelected()) || brandField.getText().isEmpty() 
                || bpkbField.getText().isEmpty() || stnkField.getText().isEmpty() 
                || namaField.getText().isEmpty() || simField.getText().isEmpty() 
                || ktpField.getText().isEmpty() || umurField.getText().isEmpty() 
                || !(pRadioButton.isSelected() || lRadioButton.isSelected()));
    }
    
    private void insertAfterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertAfterButtonActionPerformed
        ubahButton.setEnabled(false);
        hapusButton.setEnabled(false);
        makeButton.setEnabled(false);
        simpanButton.setEnabled(false); 
        batalButton.setEnabled(true);
        
        if(inputIsEmpty()){
            JOptionPane.showMessageDialog(null, "Masih ada nilai yang kosong, silakan dilengkapi");
            motorRadioButton.requestFocus();
            return;
        } else {
            try{
                Kendaraan newKend;
                newKend = createKend();
                newKend.setStatus("parkir");

                int row = kendaraanTable.getSelectedRow();
                String platPatokan = kendaraanTable.getValueAt(row, 1).toString();
                listKend.insertAfter(newKend, listKend.linearSearch(platPatokan));
                setTable();
                
                ubahButton.setEnabled(true);
                hapusButton.setEnabled(true);
                makeButton.setEnabled(true);
                simpanButton.setEnabled(false); 
                batalButton.setEnabled(false);
                clearKendaraan();
                clearPerson();
                setDisabledKomponen();
            } catch (Throwable e){
                JOptionPane.showMessageDialog(null, "Pilih row sebagai patokan");
            }
        }
    }//GEN-LAST:event_insertAfterButtonActionPerformed

    private void insertLastButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertLastButtonActionPerformed
        ubahButton.setEnabled(false);
        hapusButton.setEnabled(false);
        makeButton.setEnabled(false);
        simpanButton.setEnabled(false); 
        batalButton.setEnabled(true);
            
        if(inputIsEmpty()){
            JOptionPane.showMessageDialog(null, "Masih ada nilai yang kosong, silakan dilengkapi");
            motorRadioButton.requestFocus();
            return;
        } else {
            Kendaraan newKend;
            newKend = createKend();
            newKend.setStatus("parkir");
            listKend.insertLast(newKend);
            setTable();
            
            ubahButton.setEnabled(true);
            hapusButton.setEnabled(true);
            makeButton.setEnabled(true);
            simpanButton.setEnabled(false); 
            batalButton.setEnabled(false);
            clearKendaraan();
            clearPerson();
            setDisabledKomponen();
        }
    }//GEN-LAST:event_insertLastButtonActionPerformed
    
    private void insertFirstButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertFirstButtonActionPerformed
        ubahButton.setEnabled(false);
        hapusButton.setEnabled(false);
        makeButton.setEnabled(false);
        simpanButton.setEnabled(false); // simpan dan batal aktifkan
        batalButton.setEnabled(true);
            
        if(inputIsEmpty()){
            JOptionPane.showMessageDialog(null, "Masih ada nilai yang kosong, silakan dilengkapi");
            motorRadioButton.requestFocus();
            return;
        } else {
            Kendaraan newKend;
            newKend = createKend();
            newKend.setStatus("parkir");
            listKend.insertFirst(newKend);
            setTable();
            
            ubahButton.setEnabled(true);
            hapusButton.setEnabled(true);
            makeButton.setEnabled(true);
            simpanButton.setEnabled(false); 
            batalButton.setEnabled(false);
            clearKendaraan();
            clearPerson();
            setDisabledKomponen();
        }
    }//GEN-LAST:event_insertFirstButtonActionPerformed
    
    private void rowToForm() {
        int kolom = 1;
        int row = kendaraanTable.getSelectedRow();
        String platPatokan = kendaraanTable.getValueAt(row, 1).toString();
        Kendaraan rowKend = this.listKend.linearSearch(platPatokan);
        
        if (rowKend.getJenis().equals("motor")){
            motorRadioButton.setSelected(true);
            mobilRadioButton.setSelected(false);
            trukRadioButton.setSelected(false);
        } else if (rowKend.getJenis().equals("mobil")){
            motorRadioButton.setSelected(false);
            mobilRadioButton.setSelected(true);
            trukRadioButton.setSelected(false);
        } else if (rowKend.getJenis().equals("truk")){
            motorRadioButton.setSelected(false);
            mobilRadioButton.setSelected(false);
            trukRadioButton.setSelected(true);
        }
        platField.setText(platPatokan);
        brandField.setText(rowKend.getNamaBrand());
        bpkbField.setText(rowKend.getBpkb());
        stnkField.setText(rowKend.getStnk());
        namaField.setText(rowKend.getPersons().getNama());
        simField.setText(rowKend.getPersons().getSim());        
        ktpField.setText(rowKend.getPersons().getKtp());   
        if (rowKend.getPersons().getJk().equals("L")){
            lRadioButton.setSelected(true);
            pRadioButton.setSelected(false);
        } else if (rowKend.getPersons().getJk().equals("P")){
            lRadioButton.setSelected(false);
            pRadioButton.setSelected(true);
        }   
        umurField.setText(String.valueOf(rowKend.getPersons().getUmur()));   
        
        setEnabledKomponen();
        ubahButton.setEnabled(false);
        hapusButton.setEnabled(false);
        makeButton.setEnabled(false);
        simpanButton.setEnabled(true); 
        batalButton.setEnabled(true);
    }
    
    /**
     * @Desc
     * 
     */
    private void setTable(){
        int count = 1, total = 0, row = 0;
        
        Kendaraan bantu = listKend.getKendaraan();
        while (bantu != null) {
            int kolom = 0;
            Waktu durasiPark = bantu.getKeluar().hitungDurasiParkir(bantu.getDatang()); // Passing object
            String status = bantu.getStatus();

            kendaraanTable.setValueAt(count++, row, kolom++);
            kendaraanTable.setValueAt(bantu.getPlatKend(), row, kolom++);
            kendaraanTable.setValueAt(bantu.getJenis(), row, kolom++);
            kendaraanTable.setValueAt(bantu.getDatang().konversiToMilitary(), row, kolom++);
            if(status.equalsIgnoreCase("keluar")){
                kendaraanTable.setValueAt(bantu.getKeluar().konversiToMilitary(), row, kolom++);
                kendaraanTable.setValueAt(bantu.getKeluar().jamParkir(durasiPark), row, kolom++);
                kendaraanTable.setValueAt("Rp. " + bantu.biayaTotal(), row, kolom++);
                total += bantu.biayaTotal();
            } else if(status.equalsIgnoreCase("parkir")){
                kendaraanTable.setValueAt(" ", row, kolom++);
                kendaraanTable.setValueAt(" ", row, kolom++);
                kendaraanTable.setValueAt(" ", row, kolom++);
            }
            kendaraanTable.setValueAt(status, row++, kolom);
            bantu = bantu.next;
        } 
        this.row = row;
        this.totalBiaya = total;
        totalBiayaLabel.setText(String.valueOf(this.totalBiaya));
    }
    
    private void deleteFirstButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteFirstButtonActionPerformed
        int confirm = JOptionPane.showConfirmDialog(null, "Yakin dihapus?", "Hapus", 1);
        if(confirm == 0){
            DefaultTableModel dm = (DefaultTableModel)kendaraanTable.getModel();
            String[] dataKosong = {"", "", "", "", "", "", "", ""}; // Data counter
        
            listKend.deleteFirst();
            dm.removeRow(0);
            dm.addRow(dataKosong); // Counter agar row tidak berkurang
            kendaraanTable.validate(); 
            setTable();
        }        
        
        ubahButton.setEnabled(true);
        hapusButton.setEnabled(true);
        makeButton.setEnabled(true);
        simpanButton.setEnabled(false); 
        batalButton.setEnabled(false);
        setDisabledKomponen();
    }//GEN-LAST:event_deleteFirstButtonActionPerformed

    private void batalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalButtonActionPerformed
        // TODO add your handling code here:
        clearKendaraan();
        clearPerson();
        
        setDisabledKomponen();
        makeButton.setEnabled(true);
        hapusButton.setEnabled(true);
        ubahButton.setEnabled(true);
        simpanButton.setEnabled(false);
        batalButton.setEnabled(false);
        exitButton.setEnabled(true);
    }//GEN-LAST:event_batalButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Goodbye!");
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void makeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeButtonActionPerformed
        setEnabledKomponen(); 
        clearKendaraan();
        clearPerson();
//        parkirTable.setEnabled(false);
        ubahButton.setEnabled(false);
        hapusButton.setEnabled(false);
        makeButton.setEnabled(false);
        simpanButton.setEnabled(false); // simpan dan batal aktifkan
        batalButton.setEnabled(true);
        
        insertFirstButton.setEnabled(true);
        insertLastButton.setEnabled(true);
        insertAfterButton.setEnabled(true);
    }//GEN-LAST:event_makeButtonActionPerformed

    private void ubahButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahButtonActionPerformed
        try{
            rowToForm();
            setEnabledKomponen();
            motorRadioButton.setEnabled(false); 
            mobilRadioButton.setEnabled(false); 
            trukRadioButton.setEnabled(false); 
            platField.requestFocus();
            kendaraanTable.setEnabled(false);
            
            ubahButton.setEnabled(false);
            hapusButton.setEnabled(false);
            makeButton.setEnabled(false);
            simpanButton.setEnabled(true); 
            batalButton.setEnabled(true);
        } catch (Throwable t){
            JOptionPane.showMessageDialog(null, "Sorot data yg akan diedit");
            hapusButton.setEnabled(true);
            makeButton.setEnabled(true);
            simpanButton.setEnabled(false);
            batalButton.setEnabled(false);
            ubahButton.setEnabled(true);
        }

    }//GEN-LAST:event_ubahButtonActionPerformed

    private void hapusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusButtonActionPerformed
        ubahButton.setEnabled(false);
        hapusButton.setEnabled(false);
        makeButton.setEnabled(false);
        simpanButton.setEnabled(false); // simpan dan batal aktifkan
        batalButton.setEnabled(true);
        
        deleteFirstButton.setEnabled(true);
        deleteLastButton.setEnabled(true);
        deleteAfterButton.setEnabled(true);
        deleteCariButton.setEnabled(true);
    }//GEN-LAST:event_hapusButtonActionPerformed

    private void simpanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanButtonActionPerformed
        int barisSimpan, row, kolom = 0;
        
        ubahButton.setEnabled(true);
        hapusButton.setEnabled(true);
        makeButton.setEnabled(true);
        simpanButton.setEnabled(false);
        batalButton.setEnabled(false);
        
        if(inputIsEmpty()){
            JOptionPane.showMessageDialog(null,"Masih ada nilai yang kosong, silakan dilengkapi");
            motorRadioButton.requestFocus();
        }
        else {
            String jk = "";
            boolean gagal = false;
            
            if(lRadioButton.isSelected()){
                jk = "L";
            } else if (pRadioButton.isSelected()){
                jk = "P";
            }
            
            do{
                try{
                    String plat = platField.getText();
                    Kendaraan bantu =  listKend.linearSearch(plat);
                    bantu.setPlatKend(platField.getText());
                    bantu.setNamaBrand(brandField.getText());
                    bantu.setBpkb(bpkbField.getText());
                    bantu.setStnk(stnkField.getText());

                    // Proses input person
                    bantu.getPersons().setNama(namaField.getText());
                    bantu.getPersons().setSim(simField.getText());
                    bantu.getPersons().setKtp(ktpField.getText());
                    bantu.getPersons().setJk(jk);
                    int umur = Integer.parseInt(umurField.getText());
                    bantu.getPersons().setUmur(umur);
                    
                } catch (Throwable e) {
                    JOptionPane.showMessageDialog(null, "Nilai non-numeric, silakan input nilai numeric!");
                    gagal = true;
                    return;
                }
            } while (gagal);
            
            setTable();   
            clearKendaraan();
            clearPerson();
            setDisabledKomponen();
        }
    }//GEN-LAST:event_simpanButtonActionPerformed

    private void setDisabledKomponen() {
        platField.setEnabled(false);
        brandField.setEnabled(false);
        bpkbField.setEnabled(false);
        stnkField.setEnabled(false);
        motorRadioButton.setEnabled(false);
        mobilRadioButton.setEnabled(false);
        trukRadioButton.setEnabled(false);
        namaField.setEnabled(false);
        simField.setEnabled(false);
        ktpField.setEnabled(false);
        umurField.setEnabled(false);
        pRadioButton.setEnabled(false);
        lRadioButton.setEnabled(false);
        insertFirstButton.setEnabled(false);
        insertLastButton.setEnabled(false);
        insertAfterButton.setEnabled(false);
        deleteFirstButton.setEnabled(false);
        deleteLastButton.setEnabled(false);
        deleteAfterButton.setEnabled(false);
        deleteCariButton.setEnabled(false);
    }
    
    private void setEnabledKomponen() {
        platField.setEnabled(true);
        brandField.setEnabled(true);
        bpkbField.setEnabled(true);
        stnkField.setEnabled(true);
        motorRadioButton.setEnabled(true);
        mobilRadioButton.setEnabled(true);
        trukRadioButton.setEnabled(true);
        namaField.setEnabled(true);
        simField.setEnabled(true);
        ktpField.setEnabled(true);
        umurField.setEnabled(true);
        pRadioButton.setEnabled(true);
        lRadioButton.setEnabled(true);
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        makeButton.setEnabled(true);
        ubahButton.setEnabled(true);
        hapusButton.setEnabled(true);
        batalButton.setEnabled(false);
        simpanButton.setEnabled(false);
        exitButton.setEnabled(true);
        
        setTable();
        setDisabledKomponen();
        clearKendaraan();
        clearPerson();
        
        makeButton.setMnemonic('M');
        ubahButton.setMnemonic('U');
        hapusButton.setMnemonic('H');
        simpanButton.setMnemonic('S');
        batalButton.setMnemonic('t');
        exitButton.setMnemonic('K');
        
        makeButton.requestFocus();
        totalBiayaLabel.setText(String.valueOf(this.totalBiaya));
    }//GEN-LAST:event_formWindowOpened

    private void deleteCariButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCariButtonActionPerformed
        try{
            if(row != 0){
                int row = kendaraanTable.getSelectedRow();
                String platPatokan = kendaraanTable.getValueAt(row, 2).toString();
                listKend.deleteSearch(listKend.linearSearch(platPatokan));            
            
                DefaultTableModel dm = (DefaultTableModel)kendaraanTable.getModel();
                String[] dataKosong = {"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""}; // Data counter

                int confirm = JOptionPane.showConfirmDialog(null, "Yakin dihapus?", "Hapus", 1);
                if(confirm == 0){
                    setTable();
                    dm.removeRow(row);
                    dm.addRow(dataKosong); // Counter agar row tidak berkurang
                    kendaraanTable.validate(); 
                    setTable();
                    
                    ubahButton.setEnabled(true);
                    hapusButton.setEnabled(true);
                    makeButton.setEnabled(true);
                    simpanButton.setEnabled(false); 
                    batalButton.setEnabled(false);
                }
            }  
        } catch (Throwable e){
            JOptionPane.showMessageDialog(null, "Pilih row sebagai patokan");
        }
    }//GEN-LAST:event_deleteCariButtonActionPerformed

    private void kendaraanTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kendaraanTableMouseClicked
        try {
            if(evt.getClickCount() == 2){
                int row = kendaraanTable.getSelectedRow();
                String platPatokan = kendaraanTable.getValueAt(row, 1).toString();
                
                DetailData detail = new DetailData();
                detail.setPlat(platPatokan);
                detail.setVisible(true);
                detail.setList(this.listKend);
                detail.setField();
                Kendaraan currKend = listKend.linearSearch(platPatokan);;
                if(currKend.getStatus().equals("keluar")){
                    detail.getCheckoutButton().setVisible(false);
                }
                
                dispose();
            }
        } catch (Throwable t){
            JOptionPane.showMessageDialog(null,"Record Kosong");
        }

    }//GEN-LAST:event_kendaraanTableMouseClicked

    private void platFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_platFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_platFieldActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemParkirWaktuSistem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemParkirWaktuSistem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemParkirWaktuSistem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemParkirWaktuSistem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemParkirWaktuSistem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batalButton;
    private javax.swing.JTextField bpkbField;
    private javax.swing.JTextField brandField;
    private javax.swing.JButton deleteAfterButton;
    private javax.swing.JButton deleteCariButton;
    private javax.swing.JButton deleteFirstButton;
    private javax.swing.JButton deleteLastButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton hapusButton;
    private javax.swing.JButton insertAfterButton;
    private javax.swing.JButton insertFirstButton;
    private javax.swing.JButton insertLastButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.ButtonGroup jkButtonGroup;
    private javax.swing.ButtonGroup kendaraanButtonGroup;
    private javax.swing.JTable kendaraanTable;
    private javax.swing.JTextField ktpField;
    private javax.swing.JRadioButton lRadioButton;
    private javax.swing.JButton makeButton;
    private javax.swing.JRadioButton mobilRadioButton;
    private javax.swing.JRadioButton motorRadioButton;
    private javax.swing.JTextField namaField;
    private javax.swing.JRadioButton pRadioButton;
    private javax.swing.JTextField platField;
    private javax.swing.JTextField simField;
    private javax.swing.JButton simpanButton;
    private javax.swing.JTextField stnkField;
    private javax.swing.JLabel totalBiayaLabel;
    private javax.swing.JRadioButton trukRadioButton;
    private javax.swing.JButton ubahButton;
    private javax.swing.JTextField umurField;
    // End of variables declaration//GEN-END:variables
}
