/*	
*  Nama	        : M. Ikhsan Fadhilah - M. Zidan Yohanza - Rifqi Muhadzib Ahdan - M. Faris Ary Prasetyo
*  NPM		: 140810210003 - 140810210021 - 140810210029 - 140810190056
*  Kelas        : A
*  Tanggal	: 30 November 2022
*  Deskripsi	: Program management sistem biaya parkir menggunakan java swing (Waktu dengan system)
**/
package App;
import KendaraanPackage.*;
import StrukturData.*;
import WaktuPackage.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author asus
 */
public class SistemParkirWaktuKetik extends javax.swing.JFrame {
    private DaftarKendaraan listKend = new DaftarKendaraan(); 
    private int totalBiaya = 0, row = 0;
    

    /**
     * Creates new form SistemParkir
     */
    public SistemParkirWaktuKetik() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jkButtonGroup = new javax.swing.ButtonGroup();
        kendaraanButtonGroup = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        platField = new javax.swing.JTextField();
        brandField = new javax.swing.JTextField();
        bpkbField = new javax.swing.JTextField();
        jamMasukField = new javax.swing.JTextField();
        menitMasukField = new javax.swing.JTextField();
        detikMasukField = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jamKeluarField = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        menitKeluarField = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        detikKeluarField = new javax.swing.JTextField();
        motorRadioButton = new javax.swing.JRadioButton();
        mobilRadioButton = new javax.swing.JRadioButton();
        trukRadioButton = new javax.swing.JRadioButton();
        pJKeluarButton = new javax.swing.JButton();
        pJMasukButton = new javax.swing.JButton();
        mJMasukButton = new javax.swing.JButton();
        mMMasukButton = new javax.swing.JButton();
        pMMasukButton = new javax.swing.JButton();
        mJKeluarButton = new javax.swing.JButton();
        pMKeluarButton = new javax.swing.JButton();
        mMKeluarButton = new javax.swing.JButton();
        pDKeluarButton = new javax.swing.JButton();
        mDKeluarButton = new javax.swing.JButton();
        pDMasukButton = new javax.swing.JButton();
        mDMasukButton = new javax.swing.JButton();
        stnkField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        namaField = new javax.swing.JTextField();
        simField = new javax.swing.JTextField();
        ktpField = new javax.swing.JTextField();
        umurField = new javax.swing.JTextField();
        pRadioButton = new javax.swing.JRadioButton();
        lRadioButton = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        insertLastButton = new javax.swing.JButton();
        insertFirstButton = new javax.swing.JButton();
        insertAfterButton = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        deleteLastButton = new javax.swing.JButton();
        deleteFirstButton = new javax.swing.JButton();
        deleteAfterButton = new javax.swing.JButton();
        deleteCariButton = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        makeButton = new javax.swing.JButton();
        ubahButton = new javax.swing.JButton();
        hapusButton = new javax.swing.JButton();
        simpanButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        batalButton = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        kendaraanTable = new javax.swing.JTable();
        jScrollBar1 = new javax.swing.JScrollBar();
        jLabel17 = new javax.swing.JLabel();
        totalBiayaLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(0, 102, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Data Parkir Kendaraan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(325, 325, 325))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel8.setText("Keluar :");

        jLabel6.setText("Masuk :");

        jLabel2.setText("Jenis :");

        jLabel3.setText("Plat No :");

        jLabel4.setText("Brand :");

        jLabel5.setText("BPKB :");

        platField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                platFieldActionPerformed(evt);
            }
        });

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText(":");

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText(":");

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText(":");

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText(":");

        kendaraanButtonGroup.add(motorRadioButton);
        motorRadioButton.setText("Motor");

        kendaraanButtonGroup.add(mobilRadioButton);
        mobilRadioButton.setText("Mobil");

        kendaraanButtonGroup.add(trukRadioButton);
        trukRadioButton.setText("Truk");

        pJKeluarButton.setText("+");
        pJKeluarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pJKeluarButtonActionPerformed(evt);
            }
        });

        pJMasukButton.setText("+");
        pJMasukButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pJMasukButtonActionPerformed(evt);
            }
        });

        mJMasukButton.setText("-");
        mJMasukButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mJMasukButtonActionPerformed(evt);
            }
        });

        mMMasukButton.setText("-");
        mMMasukButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mMMasukButtonActionPerformed(evt);
            }
        });

        pMMasukButton.setText("+");
        pMMasukButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pMMasukButtonActionPerformed(evt);
            }
        });

        mJKeluarButton.setText("-");
        mJKeluarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mJKeluarButtonActionPerformed(evt);
            }
        });

        pMKeluarButton.setText("+");
        pMKeluarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pMKeluarButtonActionPerformed(evt);
            }
        });

        mMKeluarButton.setText("-");
        mMKeluarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mMKeluarButtonActionPerformed(evt);
            }
        });

        pDKeluarButton.setText("+");
        pDKeluarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pDKeluarButtonActionPerformed(evt);
            }
        });

        mDKeluarButton.setText("-");
        mDKeluarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mDKeluarButtonActionPerformed(evt);
            }
        });

        pDMasukButton.setText("+");
        pDMasukButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pDMasukButtonActionPerformed(evt);
            }
        });

        mDMasukButton.setText("-");
        mDMasukButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mDMasukButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("STNK :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(brandField))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(motorRadioButton)
                        .addGap(29, 29, 29)
                        .addComponent(trukRadioButton)
                        .addGap(33, 33, 33)
                        .addComponent(mobilRadioButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(platField))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stnkField)
                            .addComponent(bpkbField))))
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mJMasukButton)
                            .addComponent(jamMasukField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pJMasukButton)
                            .addComponent(pJKeluarButton))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(menitMasukField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(mMMasukButton)
                                    .addComponent(pMMasukButton))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(detikMasukField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(pDMasukButton)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(mDMasukButton))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(pMKeluarButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pDKeluarButton))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mJKeluarButton)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jamKeluarField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(menitKeluarField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(mMKeluarButton))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(detikKeluarField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(mDKeluarButton))))
                .addGap(0, 30, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(motorRadioButton)
                        .addComponent(trukRadioButton)
                        .addComponent(mobilRadioButton))
                    .addComponent(pJMasukButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pMMasukButton, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pDMasukButton, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jamMasukField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menitMasukField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(detikMasukField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mJMasukButton, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mMMasukButton, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mDMasukButton, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pJKeluarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pMKeluarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pDKeluarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jamKeluarField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menitKeluarField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(detikKeluarField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28)
                            .addComponent(jLabel27)
                            .addComponent(jLabel8)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(platField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(brandField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(bpkbField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(stnkField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mJKeluarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mMKeluarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mDKeluarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jLabel9.setText("Nama :");

        jLabel10.setText("SIM :");

        jLabel11.setText("KTP :");

        jLabel12.setText("Umur :");

        jLabel13.setText("JK :");

        jkButtonGroup.add(pRadioButton);
        pRadioButton.setText("P");

        jkButtonGroup.add(lRadioButton);
        lRadioButton.setText("L");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ktpField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(simField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(namaField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pRadioButton))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(umurField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel13)
                    .addComponent(namaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pRadioButton)
                    .addComponent(lRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(simField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(umurField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(ktpField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel14.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Input Person");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Input Kendaraan");

        jPanel6.setBackground(new java.awt.Color(0, 102, 51));

        insertLastButton.setText("Insert Last");
        insertLastButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertLastButtonActionPerformed(evt);
            }
        });

        insertFirstButton.setText("Insert First");
        insertFirstButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertFirstButtonActionPerformed(evt);
            }
        });

        insertAfterButton.setText("Insert After");
        insertAfterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertAfterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(insertAfterButton, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                    .addComponent(insertLastButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(insertFirstButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(insertFirstButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(insertLastButton)
                .addGap(18, 18, 18)
                .addComponent(insertAfterButton)
                .addGap(18, 18, 18))
        );

        jLabel18.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Delete");

        jPanel7.setBackground(new java.awt.Color(0, 102, 51));

        deleteLastButton.setText("Delete Last");
        deleteLastButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteLastButtonActionPerformed(evt);
            }
        });

        deleteFirstButton.setText("Delete First");
        deleteFirstButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteFirstButtonActionPerformed(evt);
            }
        });

        deleteAfterButton.setText("Delete After");
        deleteAfterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAfterButtonActionPerformed(evt);
            }
        });

        deleteCariButton.setText("Delete yg Dicari");
        deleteCariButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCariButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deleteFirstButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteAfterButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteCariButton, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                    .addComponent(deleteLastButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(deleteFirstButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(deleteLastButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteAfterButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteCariButton)
                .addGap(8, 8, 8))
        );

        jLabel20.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Insert");

        makeButton.setText("Make New");
        makeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeButtonActionPerformed(evt);
            }
        });

        ubahButton.setText("Ubah");
        ubahButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahButtonActionPerformed(evt);
            }
        });

        hapusButton.setText("Hapus");
        hapusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusButtonActionPerformed(evt);
            }
        });

        simpanButton.setText("Simpan");
        simpanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanButtonActionPerformed(evt);
            }
        });

        exitButton.setBackground(new java.awt.Color(204, 0, 0));
        exitButton.setForeground(new java.awt.Color(255, 255, 255));
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        batalButton.setText("Batal");
        batalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(makeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(hapusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(simpanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(ubahButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(batalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(29, 29, 29))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(makeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hapusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(simpanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(batalButton)
                    .addComponent(exitButton)
                    .addComponent(ubahButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 22, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel18))
                .addGap(4, 4, 4)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(8, 8, 8))
        );

        jLabel16.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Menu");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Data Parkir");

        kendaraanTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Jenis", "Plat", "Brand", "BPKB", "STNK", "Masuk", "Keluar", "Durasi", "Jam Durasi", "Biaya", "Pemilik", "SIM", "KTP", "JK", "Umur"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        kendaraanTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kendaraanTableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                kendaraanTableMouseEntered(evt);
            }
        });
        jScrollPane2.setViewportView(kendaraanTable);

        jLabel17.setText("Total Biaya : ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(169, 169, 169))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalBiayaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(372, 372, 372))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(419, 419, 419))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(totalBiayaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(191, 191, 191))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    private Kendaraan createKend() {
        Kendaraan newKend = new Kendaraan();
        String jenis = "", jk = null;
        
        if(motorRadioButton.isSelected()){
            jenis = "Motor";
        } else if(mobilRadioButton.isSelected()){
            jenis = "Mobil";
        } else if(trukRadioButton.isSelected()){
            jenis = "Truk";
        }
        
        if(lRadioButton.isSelected()){
            jk = "L";
        } else if (pRadioButton.isSelected()){
            jk = "P";
        }
        try{
            // Proses input kendaraan
            newKend = newKend.getClassKendaraan(jenis);
            newKend.setJenis(jenis);
            newKend.setPlatKend(platField.getText());
            newKend.setNamaBrand(brandField.getText());
            newKend.setBpkb(bpkbField.getText());
            newKend.setStnk(stnkField.getText());
            newKend.getDatang().setJam(Integer.parseInt(jamMasukField.getText()));
            newKend.getDatang().setMenit(Integer.parseInt(menitMasukField.getText()));
            newKend.getDatang().setDetik(Integer.parseInt(detikMasukField.getText()));
            newKend.getDatang().fixTime();
            newKend.getKeluar().setJam(Integer.parseInt(jamKeluarField.getText()));
            newKend.getKeluar().setMenit(Integer.parseInt(menitKeluarField.getText()));
            newKend.getKeluar().setDetik(Integer.parseInt(detikKeluarField.getText()));
            newKend.getKeluar().fixTime();

            // Proses input person
            newKend.getPersons().setNama(namaField.getText());
            newKend.getPersons().setSim(simField.getText());
            newKend.getPersons().setKtp(ktpField.getText());
            newKend.getPersons().setJk(jk);
            int umur = Integer.parseInt(umurField.getText());
            newKend.getPersons().setUmur(umur);
        } catch (Throwable t){
            JOptionPane.showMessageDialog(null, "Nilai non-numeric, silakan input nilai numeric!");
            newKend = null;
        }
        
        
        return newKend;
    }
    
    private void clearKendaraan(){
        kendaraanButtonGroup.clearSelection();
        platField.setText("");
        brandField.setText("");
        bpkbField.setText("");
        stnkField.setText("");
        jamMasukField.setText("");
        menitMasukField.setText("");
        detikMasukField.setText("");
        jamKeluarField.setText("");
        menitKeluarField.setText("");
        detikKeluarField.setText("");
    }
    
    private void clearPerson() {
        namaField.setText("");
        simField.setText("");
        ktpField.setText("");
        umurField.setText("");
        jkButtonGroup.clearSelection();
    }
    
    private void deleteLastButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteLastButtonActionPerformed
        listKend.deleteLast(); 
        if(row != 0){
            DefaultTableModel dm = (DefaultTableModel)kendaraanTable.getModel();
            String[] dataKosong = {"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""}; // Data counter

            int confirm = JOptionPane.showConfirmDialog(null, "Yakin dihapus?", "Hapus", 1);
            if(confirm == 0){
                setTable();
                dm.removeRow(this.row);
                dm.addRow(dataKosong); // Counter agar row tidak berkurang
                kendaraanTable.validate(); 
                setTable();
            }
        }        
        
        ubahButton.setEnabled(true);
        hapusButton.setEnabled(true);
        makeButton.setEnabled(true);
        simpanButton.setEnabled(false); 
        batalButton.setEnabled(false);
        setDisabledKomponen();
    }//GEN-LAST:event_deleteLastButtonActionPerformed

    private void deleteAfterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAfterButtonActionPerformed
        try{    
            if(row != 0){
                int row = kendaraanTable.getSelectedRow();
                String platPatokan = kendaraanTable.getValueAt(row, 2).toString();
                listKend.deleteAfter(listKend.linearSearch(platPatokan)); 
                
                DefaultTableModel dm = (DefaultTableModel)kendaraanTable.getModel();
                String[] dataKosong = {"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""}; // Data counter

                int confirm = JOptionPane.showConfirmDialog(null, "Yakin dihapus?", "Hapus", 1);
                if(confirm == 0){
                    setTable();
                    dm.removeRow(this.row);
                    dm.addRow(dataKosong); // Counter agar row tidak berkurang
                    kendaraanTable.validate(); 
                    setTable();
                    
                    ubahButton.setEnabled(true);
                    hapusButton.setEnabled(true);
                    makeButton.setEnabled(true);
                    simpanButton.setEnabled(false); 
                    batalButton.setEnabled(false);
                }
            }  
        } catch (Throwable e){
            JOptionPane.showMessageDialog(null, "Pilih row sebagai patokan");
        }
    }//GEN-LAST:event_deleteAfterButtonActionPerformed

    private boolean inputIsEmpty(){
        return(!(motorRadioButton.isSelected() || mobilRadioButton.isSelected() || trukRadioButton.isSelected()) || brandField.getText().isEmpty() 
                || bpkbField.getText().isEmpty() || stnkField.getText().isEmpty() 
                || jamMasukField.getText().isEmpty() || menitMasukField.getText().isEmpty() 
                || detikMasukField.getText().isEmpty() || jamKeluarField.getText().isEmpty() 
                || menitKeluarField.getText().isEmpty() || detikKeluarField.getText().isEmpty() 
                || namaField.getText().isEmpty() || simField.getText().isEmpty() 
                || ktpField.getText().isEmpty() || umurField.getText().isEmpty() 
                || !(pRadioButton.isSelected() || lRadioButton.isSelected()));
    }
    
    private void insertAfterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertAfterButtonActionPerformed
        ubahButton.setEnabled(false);
        hapusButton.setEnabled(false);
        makeButton.setEnabled(false);
        simpanButton.setEnabled(false); 
        batalButton.setEnabled(true);
        
        if(inputIsEmpty()){
//            jLabel19.showMessageDialog(null,"Masih ada nilai yang kosong, silakan dilengkapi");
            motorRadioButton.requestFocus();
            return;
        } else {
            try{
                Kendaraan newKend;
                newKend = createKend();

                int row = kendaraanTable.getSelectedRow();
                String platPatokan = kendaraanTable.getValueAt(row, 2).toString();
                listKend.insertAfter(newKend, listKend.linearSearch(platPatokan));
                setTable();
                
                ubahButton.setEnabled(true);
                hapusButton.setEnabled(true);
                makeButton.setEnabled(true);
                simpanButton.setEnabled(false); 
                batalButton.setEnabled(false);
                clearKendaraan();
                clearPerson();
                setDisabledKomponen();
            } catch (Throwable e){
                JOptionPane.showMessageDialog(null, "Pilih row sebagai patokan");
            }
        }
    }//GEN-LAST:event_insertAfterButtonActionPerformed

    private void insertLastButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertLastButtonActionPerformed
        ubahButton.setEnabled(false);
        hapusButton.setEnabled(false);
        makeButton.setEnabled(false);
        simpanButton.setEnabled(false); 
        batalButton.setEnabled(true);
        
        if(inputIsEmpty()){
//            jLabel19.showMessageDialog(null,"Masih ada nilai yang kosong, silakan dilengkapi");
            motorRadioButton.requestFocus();
            return;
        } else {
            Kendaraan newKend;
            newKend = createKend();
            listKend.insertLast(newKend);
            setTable();
                                        
            ubahButton.setEnabled(true);
            hapusButton.setEnabled(true);
            makeButton.setEnabled(true);
            simpanButton.setEnabled(false); 
            batalButton.setEnabled(false);
            clearKendaraan();
            clearPerson();
            setDisabledKomponen();
        }
    }//GEN-LAST:event_insertLastButtonActionPerformed
    
    private void insertFirstButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertFirstButtonActionPerformed
        ubahButton.setEnabled(false);
        hapusButton.setEnabled(false);
        makeButton.setEnabled(false);
        simpanButton.setEnabled(false); // simpan dan batal aktifkan
        batalButton.setEnabled(true);
            
        if(inputIsEmpty()){
//            jLabel19.showMessageDialog(null,"Masih ada nilai yang kosong, silakan dilengkapi");
            motorRadioButton.requestFocus();
            return;
        } else {
            Kendaraan newKend;
            newKend = createKend();
            listKend.insertFirst(newKend);
            setTable();
            
            ubahButton.setEnabled(true);
            hapusButton.setEnabled(true);
            makeButton.setEnabled(true);
            simpanButton.setEnabled(false); 
            batalButton.setEnabled(false);
            clearKendaraan();
            clearPerson();
            setDisabledKomponen();
        }
    }//GEN-LAST:event_insertFirstButtonActionPerformed
    
    private void rowToForm() {
        int kolom = 1;
        int row = kendaraanTable.getSelectedRow();
        
        if (kendaraanTable.getValueAt(row, kolom).toString().equals("motor")){
            motorRadioButton.setSelected(true);
            mobilRadioButton.setSelected(false);
            trukRadioButton.setSelected(false);
        } else if (kendaraanTable.getValueAt(row, kolom).toString().equals("mobil")){
            motorRadioButton.setSelected(false);
            mobilRadioButton.setSelected(true);
            trukRadioButton.setSelected(false);
        } else if (kendaraanTable.getValueAt(row, kolom).toString().equals("truk")){
            motorRadioButton.setSelected(false);
            mobilRadioButton.setSelected(false);
            trukRadioButton.setSelected(true);
        }
        kolom++;
        platField.setText(kendaraanTable.getValueAt(row, kolom++).toString());
        brandField.setText(kendaraanTable.getValueAt(row, kolom++).toString());
        bpkbField.setText(kendaraanTable.getValueAt(row, kolom++).toString());
        stnkField.setText(kendaraanTable.getValueAt(row, kolom++).toString());
        jamMasukField.setText(kendaraanTable.getValueAt(row, kolom).toString().substring(0, 2));
        menitMasukField.setText(kendaraanTable.getValueAt(row, kolom).toString().substring(3, 5));
        detikMasukField.setText(kendaraanTable.getValueAt(row, kolom++).toString().substring(6, 8));
        jamKeluarField.setText(kendaraanTable.getValueAt(row, kolom).toString().substring(0, 2));
        menitKeluarField.setText(kendaraanTable.getValueAt(row, kolom).toString().substring(3, 5));
        detikKeluarField.setText(kendaraanTable.getValueAt(row, kolom++).toString().substring(6, 8));
        kolom += 3;
        namaField.setText(kendaraanTable.getValueAt(row, kolom++).toString());
        simField.setText(kendaraanTable.getValueAt(row, kolom++).toString());        
        ktpField.setText(kendaraanTable.getValueAt(row, kolom++).toString());   
        if (kendaraanTable.getValueAt(row, kolom).toString().equals("L")){
            lRadioButton.setSelected(true);
            pRadioButton.setSelected(false);
        } else if (kendaraanTable.getValueAt(row, kolom).toString().equals("P")){
            lRadioButton.setSelected(false);
            pRadioButton.setSelected(true);
        }   
        kolom++;
        umurField.setText(kendaraanTable.getValueAt(row, kolom++).toString());   
        
        setEnabledKomponen();
        ubahButton.setEnabled(false);
        hapusButton.setEnabled(false);
        makeButton.setEnabled(false);
        simpanButton.setEnabled(true); 
        batalButton.setEnabled(true);
    }
    
    /**
     * @Desc
     * 
     */
    private void setTable(){
        int count = 1, total = 0, row = 0;
        
        Kendaraan bantu = listKend.getKendaraan();
        if(bantu !=  null){
            do {
                int kolom = 0;
                Waktu durasiPark = bantu.getKeluar().hitungDurasiParkir(bantu.getDatang()); // Passing object
                
                kendaraanTable.setValueAt(count++, row, kolom++);
                kendaraanTable.setValueAt(bantu.getJenis(), row, kolom++);
                kendaraanTable.setValueAt(bantu.getPlatKend(), row, kolom++);
                kendaraanTable.setValueAt(bantu.getNamaBrand(), row, kolom++);
                kendaraanTable.setValueAt(bantu.getBpkb(), row, kolom++);
                kendaraanTable.setValueAt(bantu.getStnk(), row, kolom++);
                kendaraanTable.setValueAt(bantu.getDatang().konversiToMilitary(), row, kolom++);
                kendaraanTable.setValueAt(bantu.getKeluar().konversiToMilitary(), row, kolom++);
                kendaraanTable.setValueAt(durasiPark.konversiToMilitary(), row, kolom++);
                kendaraanTable.setValueAt(bantu.getKeluar().jamParkir(durasiPark), row, kolom++);
                kendaraanTable.setValueAt(bantu.biayaTotal(), row, kolom++);
                
                kendaraanTable.setValueAt(bantu.getPersons().getNama(), row, kolom++);
                kendaraanTable.setValueAt(bantu.getPersons().getSim(), row, kolom++);
                kendaraanTable.setValueAt(bantu.getPersons().getKtp(), row, kolom++);
                kendaraanTable.setValueAt(bantu.getPersons().getJk(), row, kolom++);
                kendaraanTable.setValueAt(bantu.getPersons().getUmur(), row++, kolom++);
                
                total += bantu.biayaTotal();
                bantu = bantu.next;
            } while (bantu != null);
        }
        this.row = row;
        this.totalBiaya = total;
        totalBiayaLabel.setText(String.valueOf(this.totalBiaya));
    }
    
//    private void set
    
    private void deleteFirstButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteFirstButtonActionPerformed
        listKend.deleteFirst(); 
        DefaultTableModel dm = (DefaultTableModel)kendaraanTable.getModel();
        String[] dataKosong = {"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""}; // Data counter
        
        int confirm = JOptionPane.showConfirmDialog(null, "Yakin dihapus?", "Hapus", 1);
        if(confirm == 0){
            dm.removeRow(0);
            dm.addRow(dataKosong); // Counter agar row tidak berkurang
            kendaraanTable.validate(); 
            setTable();
        }        
        
        ubahButton.setEnabled(true);
        hapusButton.setEnabled(true);
        makeButton.setEnabled(true);
        simpanButton.setEnabled(false); 
        batalButton.setEnabled(false);
        setDisabledKomponen();
    }//GEN-LAST:event_deleteFirstButtonActionPerformed

    private void batalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalButtonActionPerformed
        // TODO add your handling code here:
        clearKendaraan();
        clearPerson();
        
        setDisabledKomponen();
        makeButton.setEnabled(true);
        hapusButton.setEnabled(true);
        ubahButton.setEnabled(true);
        simpanButton.setEnabled(true);
        batalButton.setEnabled(false);
        exitButton.setEnabled(true);
    }//GEN-LAST:event_batalButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Goodbye!");
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void makeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeButtonActionPerformed
        setEnabledKomponen(); 
        clearKendaraan();
        clearPerson();
//        parkirTable.setEnabled(false);
        ubahButton.setEnabled(false);
        hapusButton.setEnabled(false);
        makeButton.setEnabled(false);
        simpanButton.setEnabled(false); // simpan dan batal aktifkan
        batalButton.setEnabled(true);
        
        insertFirstButton.setEnabled(true);
        insertLastButton.setEnabled(true);
        insertAfterButton.setEnabled(true);
        
        jamMasukField.setText("0");
        menitMasukField.setText("0");
        detikMasukField.setText("0");
        jamKeluarField.setText("0");
        menitKeluarField.setText("0");
        detikKeluarField.setText("0");
    }//GEN-LAST:event_makeButtonActionPerformed

    private void ubahButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahButtonActionPerformed
        try{
            rowToForm();
            setEnabledKomponen();
            motorRadioButton.setEnabled(false); 
            mobilRadioButton.setEnabled(false); 
            trukRadioButton.setEnabled(false); 
            platField.requestFocus();
            kendaraanTable.setEnabled(false);
            
            ubahButton.setEnabled(false);
            hapusButton.setEnabled(false);
            makeButton.setEnabled(false);
            simpanButton.setEnabled(true); 
            batalButton.setEnabled(true);
        } catch (Throwable t){
            JOptionPane.showMessageDialog(null, "Sorot data yg akan diedit");
            hapusButton.setEnabled(true);
            makeButton.setEnabled(true);
            simpanButton.setEnabled(false);
            batalButton.setEnabled(false);
            ubahButton.setEnabled(true);
        }

    }//GEN-LAST:event_ubahButtonActionPerformed

    private void hapusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusButtonActionPerformed
        ubahButton.setEnabled(false);
        hapusButton.setEnabled(false);
        makeButton.setEnabled(false);
        simpanButton.setEnabled(false); // simpan dan batal aktifkan
        batalButton.setEnabled(true);
        
        deleteFirstButton.setEnabled(true);
        deleteLastButton.setEnabled(true);
        deleteAfterButton.setEnabled(true);
        deleteCariButton.setEnabled(true);
    }//GEN-LAST:event_hapusButtonActionPerformed

    private void simpanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanButtonActionPerformed
        int barisSimpan, row, kolom = 0;
        
        ubahButton.setEnabled(true);
        hapusButton.setEnabled(true);
        makeButton.setEnabled(true);
        simpanButton.setEnabled(false);
        batalButton.setEnabled(false);
        
        if(inputIsEmpty()){
            JOptionPane.showMessageDialog(null,"Masih ada nilai yang kosong, silakan dilengkapi");
            motorRadioButton.requestFocus();
        }
        else {
            String jk = "";
            
            if(lRadioButton.isSelected()){
                jk = "L";
            } else if (pRadioButton.isSelected()){
                jk = "P";
            }
            
            try{
                String plat = platField.getText();
                Kendaraan bantu =  listKend.linearSearch(plat);
                bantu.setPlatKend(platField.getText());
                bantu.setNamaBrand(brandField.getText());
                bantu.setBpkb(bpkbField.getText());
                bantu.setStnk(stnkField.getText());
                bantu.getDatang().setJam(Integer.parseInt(jamMasukField.getText()));
                bantu.getDatang().setMenit(Integer.parseInt(menitMasukField.getText()));
                bantu.getDatang().setDetik(Integer.parseInt(detikMasukField.getText()));
                bantu.getDatang().fixTime();
                bantu.getKeluar().setJam(Integer.parseInt(jamKeluarField.getText()));
                bantu.getKeluar().setMenit(Integer.parseInt(menitKeluarField.getText()));
                bantu.getKeluar().setDetik(Integer.parseInt(detikKeluarField.getText()));
                bantu.getKeluar().fixTime();

                // Proses input person
                bantu.getPersons().setNama(namaField.getText());
                bantu.getPersons().setSim(simField.getText());
                bantu.getPersons().setKtp(ktpField.getText());
                bantu.getPersons().setJk(jk);
                int umur = Integer.parseInt(umurField.getText());
                bantu.getPersons().setUmur(umur);
                
                setTable();   
                clearKendaraan();
                clearPerson();
                setDisabledKomponen();
            } catch (Throwable e) {
                JOptionPane.showMessageDialog(null, "Nilai non-numeric, silakan input nilai numeric!");
                return;
            }
        }
    }//GEN-LAST:event_simpanButtonActionPerformed

    private void setDisabledKomponen() {
        platField.setEnabled(false);
        brandField.setEnabled(false);
        bpkbField.setEnabled(false);
        stnkField.setEnabled(false);
        motorRadioButton.setEnabled(false);
        mobilRadioButton.setEnabled(false);
        trukRadioButton.setEnabled(false);
        jamMasukField.setEnabled(false);
        menitMasukField.setEnabled(false);
        detikMasukField.setEnabled(false);
        jamKeluarField.setEnabled(false);
        menitKeluarField.setEnabled(false);
        detikKeluarField.setEnabled(false);
        pJMasukButton.setEnabled(false);
        pMMasukButton.setEnabled(false);
        pDMasukButton.setEnabled(false);
        pJKeluarButton.setEnabled(false);
        pMKeluarButton.setEnabled(false);
        pDKeluarButton.setEnabled(false);
        mJMasukButton.setEnabled(false);
        mMMasukButton.setEnabled(false);
        mDMasukButton.setEnabled(false);
        mJKeluarButton.setEnabled(false);
        mMKeluarButton.setEnabled(false);
        mDKeluarButton.setEnabled(false);
        namaField.setEnabled(false);
        simField.setEnabled(false);
        ktpField.setEnabled(false);
        umurField.setEnabled(false);
        pRadioButton.setEnabled(false);
        lRadioButton.setEnabled(false);
        insertFirstButton.setEnabled(false);
        insertLastButton.setEnabled(false);
        insertAfterButton.setEnabled(false);
        deleteFirstButton.setEnabled(false);
        deleteLastButton.setEnabled(false);
        deleteAfterButton.setEnabled(false);
        deleteCariButton.setEnabled(false);
    }
    
    private void setEnabledKomponen() {
        platField.setEnabled(true);
        brandField.setEnabled(true);
        bpkbField.setEnabled(true);
        stnkField.setEnabled(true);
        motorRadioButton.setEnabled(true);
        mobilRadioButton.setEnabled(true);
        trukRadioButton.setEnabled(true);
        jamMasukField.setEnabled(true);
        menitMasukField.setEnabled(true);
        detikMasukField.setEnabled(true);
        jamKeluarField.setEnabled(true);
        menitKeluarField.setEnabled(true);
        detikKeluarField.setEnabled(true);
        pJMasukButton.setEnabled(true);
        pMMasukButton.setEnabled(true);
        pDMasukButton.setEnabled(true);
        pJKeluarButton.setEnabled(true);
        pMKeluarButton.setEnabled(true);
        pDKeluarButton.setEnabled(true);
        mJMasukButton.setEnabled(true);
        mMMasukButton.setEnabled(true);
        mDMasukButton.setEnabled(true);
        mJKeluarButton.setEnabled(true);
        mMKeluarButton.setEnabled(true);
        mDKeluarButton.setEnabled(true);
        namaField.setEnabled(true);
        simField.setEnabled(true);
        ktpField.setEnabled(true);
        umurField.setEnabled(true);
        pRadioButton.setEnabled(true);
        lRadioButton.setEnabled(true);
//        insertFirstButton.setEnabled(true);
//        insertLastButton.setEnabled(true);
//        insertAfterButton.setEnabled(true);
//        deleteFirstButton.setEnabled(true);
//        deleteLastButton.setEnabled(true);
//        deleteAfterButton.setEnabled(true);
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        makeButton.setEnabled(true);
        ubahButton.setEnabled(true);
        hapusButton.setEnabled(true);
        batalButton.setEnabled(false);
        exitButton.setEnabled(true);
        
        setDisabledKomponen();
        clearKendaraan();
        clearPerson();
        
        makeButton.setMnemonic('M');
        ubahButton.setMnemonic('U');
        hapusButton.setMnemonic('H');
        simpanButton.setMnemonic('S');
        batalButton.setMnemonic('t');
        exitButton.setMnemonic('K');
        
        makeButton.requestFocus();
        totalBiayaLabel.setText(String.valueOf(this.totalBiaya));
    }//GEN-LAST:event_formWindowOpened

    private void deleteCariButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCariButtonActionPerformed
        try{
            if(row != 0){
                int row = kendaraanTable.getSelectedRow();
                String platPatokan = kendaraanTable.getValueAt(row, 2).toString();
                listKend.deleteSearch(listKend.linearSearch(platPatokan));            
            
                DefaultTableModel dm = (DefaultTableModel)kendaraanTable.getModel();
                String[] dataKosong = {"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""}; // Data counter

                int confirm = JOptionPane.showConfirmDialog(null, "Yakin dihapus?", "Hapus", 1);
                if(confirm == 0){
                    setTable();
                    dm.removeRow(this.row);
                    dm.addRow(dataKosong); // Counter agar row tidak berkurang
                    kendaraanTable.validate(); 
                    setTable();
                    
                    ubahButton.setEnabled(true);
                    hapusButton.setEnabled(true);
                    makeButton.setEnabled(true);
                    simpanButton.setEnabled(false); 
                    batalButton.setEnabled(false);
                }
            }  
        } catch (Throwable e){
            JOptionPane.showMessageDialog(null, "Pilih row sebagai patokan");
        }
    }//GEN-LAST:event_deleteCariButtonActionPerformed

    private void kendaraanTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kendaraanTableMouseClicked
        try {
            if(evt.getClickCount() == 2){
                rowToForm();
                setEnabledKomponen();
                motorRadioButton.setEnabled(false); 
                mobilRadioButton.setEnabled(false); 
                trukRadioButton.setEnabled(false); 
                platField.requestFocus();
                kendaraanTable.setEnabled(false);

                ubahButton.setEnabled(false);
                hapusButton.setEnabled(false);
                makeButton.setEnabled(false);
                simpanButton.setEnabled(true); 
                batalButton.setEnabled(true);
            }
        } catch (Throwable t){
            JOptionPane.showMessageDialog(null,"Record Kosong");
        }

    }//GEN-LAST:event_kendaraanTableMouseClicked

    private void kendaraanTableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kendaraanTableMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_kendaraanTableMouseEntered

    private void platFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_platFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_platFieldActionPerformed

    private void pMMasukButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pMMasukButtonActionPerformed
        menitMasukField.setText(String.valueOf(Integer.parseInt(menitMasukField.getText()) + 1));
    }//GEN-LAST:event_pMMasukButtonActionPerformed

    private void pDMasukButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pDMasukButtonActionPerformed
        detikMasukField.setText(String.valueOf(Integer.parseInt(detikMasukField.getText()) + 1));
    }//GEN-LAST:event_pDMasukButtonActionPerformed

    private void mMMasukButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mMMasukButtonActionPerformed
        int menit = Integer.parseInt(menitMasukField.getText()) - 1;
        if(menit >= 0){
            menitMasukField.setText(String.valueOf(menit));
        }
    }//GEN-LAST:event_mMMasukButtonActionPerformed

    private void mDMasukButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mDMasukButtonActionPerformed
        int detik = Integer.parseInt(detikMasukField.getText()) - 1;
        if(detik >= 0){
            detikMasukField.setText(String.valueOf(detik));
        }
    }//GEN-LAST:event_mDMasukButtonActionPerformed

    private void pJKeluarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pJKeluarButtonActionPerformed
        jamKeluarField.setText(String.valueOf(Integer.parseInt(jamKeluarField.getText()) + 1));
    }//GEN-LAST:event_pJKeluarButtonActionPerformed

    private void pMKeluarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pMKeluarButtonActionPerformed
        menitKeluarField.setText(String.valueOf(Integer.parseInt(menitKeluarField.getText()) + 1));
    }//GEN-LAST:event_pMKeluarButtonActionPerformed

    private void pDKeluarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pDKeluarButtonActionPerformed
        detikKeluarField.setText(String.valueOf(Integer.parseInt(detikKeluarField.getText()) + 1));
    }//GEN-LAST:event_pDKeluarButtonActionPerformed

    private void mJKeluarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mJKeluarButtonActionPerformed
        int jam = Integer.parseInt(jamKeluarField.getText()) - 1;
        if(jam >= 0){
            jamKeluarField.setText(String.valueOf(jam));
        }
    }//GEN-LAST:event_mJKeluarButtonActionPerformed

    private void mMKeluarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mMKeluarButtonActionPerformed
        int menit = Integer.parseInt(menitKeluarField.getText()) - 1;
        if(menit >= 0){
            menitKeluarField.setText(String.valueOf(menit));
        }
    }//GEN-LAST:event_mMKeluarButtonActionPerformed

    private void mDKeluarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mDKeluarButtonActionPerformed
        int detik = Integer.parseInt(detikKeluarField.getText()) - 1;
        if(detik >= 0){
            detikKeluarField.setText(String.valueOf(detik));
        }
    }//GEN-LAST:event_mDKeluarButtonActionPerformed

    private void mJMasukButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mJMasukButtonActionPerformed
        int jam = Integer.parseInt(jamMasukField.getText()) - 1;
        if(jam >= 0){
            jamMasukField.setText(String.valueOf(jam));
        }
    }//GEN-LAST:event_mJMasukButtonActionPerformed

    private void pJMasukButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pJMasukButtonActionPerformed
        jamMasukField.setText(String.valueOf(Integer.parseInt(jamMasukField.getText()) + 1));
    }//GEN-LAST:event_pJMasukButtonActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemParkirWaktuKetik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemParkirWaktuKetik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemParkirWaktuKetik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemParkirWaktuKetik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemParkirWaktuKetik().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batalButton;
    private javax.swing.JTextField bpkbField;
    private javax.swing.JTextField brandField;
    private javax.swing.JButton deleteAfterButton;
    private javax.swing.JButton deleteCariButton;
    private javax.swing.JButton deleteFirstButton;
    private javax.swing.JButton deleteLastButton;
    private javax.swing.JTextField detikKeluarField;
    private javax.swing.JTextField detikMasukField;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton hapusButton;
    private javax.swing.JButton insertAfterButton;
    private javax.swing.JButton insertFirstButton;
    private javax.swing.JButton insertLastButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jamKeluarField;
    private javax.swing.JTextField jamMasukField;
    private javax.swing.ButtonGroup jkButtonGroup;
    private javax.swing.ButtonGroup kendaraanButtonGroup;
    private javax.swing.JTable kendaraanTable;
    private javax.swing.JTextField ktpField;
    private javax.swing.JRadioButton lRadioButton;
    private javax.swing.JButton mDKeluarButton;
    private javax.swing.JButton mDMasukButton;
    private javax.swing.JButton mJKeluarButton;
    private javax.swing.JButton mJMasukButton;
    private javax.swing.JButton mMKeluarButton;
    private javax.swing.JButton mMMasukButton;
    private javax.swing.JButton makeButton;
    private javax.swing.JTextField menitKeluarField;
    private javax.swing.JTextField menitMasukField;
    private javax.swing.JRadioButton mobilRadioButton;
    private javax.swing.JRadioButton motorRadioButton;
    private javax.swing.JTextField namaField;
    private javax.swing.JButton pDKeluarButton;
    private javax.swing.JButton pDMasukButton;
    private javax.swing.JButton pJKeluarButton;
    private javax.swing.JButton pJMasukButton;
    private javax.swing.JButton pMKeluarButton;
    private javax.swing.JButton pMMasukButton;
    private javax.swing.JRadioButton pRadioButton;
    private javax.swing.JTextField platField;
    private javax.swing.JTextField simField;
    private javax.swing.JButton simpanButton;
    private javax.swing.JTextField stnkField;
    private javax.swing.JLabel totalBiayaLabel;
    private javax.swing.JRadioButton trukRadioButton;
    private javax.swing.JButton ubahButton;
    private javax.swing.JTextField umurField;
    // End of variables declaration//GEN-END:variables
}
